export const Dados = [{
    status: "Delivered",
    sender:"Ford",
    receiver:"Camila",
    document:"Acknowledgement",
    content:"",
    size:"",
    connection:"Sintel",
    data:"",
    ID:"1",
    downloadFile:"",
    viewDetails:"",
},
{
    status: "EDI Ack Accepted",
    sender:"Renault",
    receiver:"Tupy Mexico",
    document:"Acknowledgement",
    content:"",
    size:"",
    connection:"Sintel",
    data:"",
    ID:"2",
    downloadFile:"",
    viewDetails:"",
},
{
    status: "Failure",
    sender:"Honda",
    receiver:"Tupy Mexico",
    document:"Acknowledgement",
    content:"",
    size:"",
    connection:"Sintel",
    data:"",
    ID:"3",
    downloadFile:"",
    viewDetails:"",
},
{
    status: "Sent",
    sender:"Renault",
    receiver:"Tupy Mexico",
    document:"Acknowledgement",
    content:"",
    size:"",
    connection:"Sintel",
    data:"",
    ID:"4",
    downloadFile:"",
    viewDetails:"",
},
{
    status: "Delivered",
    sender:"Honda",
    receiver:"Tupy Mexico",
    document:"Acknowledgement",
    content:"",
    size:"",
    connection:"Sintel",
    data:"",
    ID:"5",
    downloadFile:"",
    viewDetails:"",
},
{
    status: "Sent",
    sender:"Renault",
    receiver:"Tupy Mexico",
    document:"Acknowledgement",
    content:"",
    size:"",
    connection:"Sintel",
    data:"",
    ID:"6",
    downloadFile:"",
    viewDetails:"",
},
{
    status: "Delivered",
    sender:"FIAT",
    receiver:"Tupy Mexico",
    document:"Acknowledgement",
    content:"",
    size:"",
    connection:"Sintel",
    data:"",
    ID:"7",
    downloadFile:"",
    viewDetails:"",
},
{
    status: "EDI Ack Accepted",
    sender:"Ford",
    receiver:"Tupy Mexico",
    document:"Acknowledgement",
    content:"",
    size:"",
    connection:"Sintel",
    data:"",
    ID:"8",
    downloadFile:"",
    viewDetails:"",
},
{
    status: "Sent",
    sender:"Renault",
    receiver:"Tupy Mexico",
    document:"Acknowledgement",
    content:"",
    size:"",
    connection:"Sintel",
    data:"",
    ID:"9",
    downloadFile:"",
    viewDetails:"",
},
{
    status: "Failure",
    sender:"FIAT",
    receiver:"Tupy Mexico",
    document:"Acknowledgement",
    content:"",
    size:"",
    connection:"Sintel",
    data:"",
    ID:"10",
    downloadFile:"",
    viewDetails:"",
},
{
    status: "EDI Ack Accepted",
    sender:"Honda",
    receiver:"Tupy Mexico",
    document:"Acknowledgement",
    content:"",
    size:"",
    connection:"Sintel",
    data:"",
    ID:"11",
    downloadFile:"",
    viewDetails:"",
},
{
    status: "EDI Ack Accepted",
    sender:"Renault",
    receiver:"Tupy Mexico",
    document:"Acknowledgement",
    content:"",
    size:"",
    connection:"Sintel",
    data:"",
    ID:"12",
    downloadFile:"",
    viewDetails:"",
},
{
    status: "Delivered",
    sender:"Ford",
    receiver:"Tupy Mexico",
    document:"Acknowledgement",
    content:"",
    size:"",
    connection:"Sintel",
    data:"",
    ID:"13",
    downloadFile:"",
    viewDetails:"",
},
{
    status: "EDI Ack Accepted",
    sender:"Ford",
    receiver:"Tupy Mexico",
    document:"Acknowledgement",
    content:"",
    size:"",
    connection:"Sintel",
    data:"",
    ID:"14",
    downloadFile:"",
    viewDetails:"",
},
{
    status: "Failure",
    sender:"FIAT",
    receiver:"Tupy Mexico",
    document:"Acknowledgement",
    content:"",
    size:"",
    connection:"Sintel",
    data:"",
    ID:"15",
    downloadFile:"",
    viewDetails:"",
},
{
    status: "EDI Ack Accepted",
    sender:"FIAT",
    receiver:"Tupy Mexico",
    document:"Acknowledgement",
    content:"",
    size:"",
    connection:"Sintel",
    data:"",
    ID:"16",
    downloadFile:"",
    viewDetails:"",
},
];
    
